services:
  base: &base
    image: edwin:dev
    env_file: .env
    volumes:
      - ./source:/home/node/app
      - ./docker_volumes/node_modules:/home/node/app/node_modules

  base_build:
    <<: *base
    container_name: edwin_build
    build:
      context: .
      dockerfile: dockerfiles/dev_edwin/Dockerfile
    command: echo done

  edwin_dev:
    <<: *base
    container_name: edwin_dev
    depends_on: [base_build]
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: /bin/bash

  basic_example:
    image: edwin:dev
    container_name: basic_example
    depends_on: [base_build]
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./examples/basic-rpg:/home/node/app
      - ./source:/home/node/app/edwin
      - ./docker_volumes/node_modules:/home/node/app/node_modules
    stdin_open: true
    tty: true
    command: npx vite --host 0.0.0.0 --port 3000

  advanced_example:
    image: edwin:dev
    container_name: advanced_example
    depends_on: [base_build]
    environment:
      - NODE_ENV=development
    ports:
      - "3010:3010"
    volumes:
      - ./examples/advanced-rpg:/home/node/app
      - ./source:/home/node/app/edwin
      - ./docker_volumes/node_modules:/home/node/app/node_modules
    stdin_open: true
    tty: true
    command: npx vite --host 0.0.0.0 --port 3010

  personal_marketing_example:
    image: edwin:dev
    container_name: personal_marketing_example
    depends_on: [base_build]
    environment:
      - NODE_ENV=development
    ports:
      - "3050:3050"
    volumes:
      - ./examples/personal-marketing:/home/node/app
      - ./source:/home/node/app/edwin
      - ./docker_volumes/node_modules:/home/node/app/node_modules
    stdin_open: true
    tty: true
    command: npx vite --host 0.0.0.0 --port 3050
